title: Astronaut Reaction Time Game
hero_image: images/banner.png
description: Do you have the speedy reactions needed to be an Astronaut? Create this game to find out!
original_url: https://raspberrypi.org/learning/astronaut-reaction-times
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: space
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Getting started
- title: Set the stage with a space theme
- title: Create variables to store data
- title: Begin the reaction game script
- title: "Comparing player's reaction time to the ISS orbit"
- title: What next?
